-- Name: tdb_database; Type: TABLE;
--

CREATE TABLE public.tdb_database (
    db_dbid integer NOT NULL,
    db_name character varying(16) NOT NULL
);

ALTER TABLE public.tdb_database ALTER COLUMN db_dbid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tdb_database_db_dbid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.tdb_database
    ADD CONSTRAINT tdb_database_db_dbid_key UNIQUE (db_dbid);

ALTER TABLE ONLY public.tdb_database
    ADD CONSTRAINT tdb_database_pkey PRIMARY KEY (db_name);

--
-- Name: ths_history; Type: TABLE;
--

CREATE TABLE public.ths_history (
    hs_hsid integer NOT NULL,
    hs_datetime timestamp with time zone NOT NULL,
    hs_sbid integer,
    hs_owner character varying(16) NOT NULL,
    hs_subject character varying(32),
    hs_qqid integer[],
    hs_questions integer,
    hs_ans integer[],
    hs_points integer[],
    hs_maxpoints integer,
    hs_totalpoints integer,
    hs_correctpercent integer,
    hs_usid integer,
    hs_rfid integer DEFAULT 0
);

ALTER TABLE public.ths_history ALTER COLUMN hs_hsid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ths_history_hs_hsid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.ths_history
    ADD CONSTRAINT ths_history_pkey PRIMARY KEY (hs_hsid);

CREATE INDEX idx_ths_history_hs_sbid ON public.ths_history USING btree (hs_sbid);

CREATE INDEX idx_ths_history_hs_usid ON public.ths_history USING btree (hs_usid);

--
-- Name: tow_owner; Type: TABLE;
--

CREATE TABLE public.tow_owner (
    ow_owid integer NOT NULL,
    ow_owner character varying(16) NOT NULL
);

ALTER TABLE public.tow_owner ALTER COLUMN ow_owid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tow_owner_ow_owid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.tow_owner
    ADD CONSTRAINT tow_owner_ow_owid_key UNIQUE (ow_owid);

ALTER TABLE ONLY public.tow_owner
    ADD CONSTRAINT tow_owner_pkey PRIMARY KEY (ow_owner);

--
-- Name: tqq_questions; Type: TABLE;
--

CREATE TABLE public.tqq_questions (
    qq_qqid integer NOT NULL,
    qq_owner character varying(16) NOT NULL,
    qq_subject character varying(32) NOT NULL,
    qq_sbid integer NOT NULL,
    qq_seq smallint NOT NULL,
    qq_detail character varying(256),
    qq_points integer[],
    qq_ans text[],
    qq_rounds text[],
    qq_north text[],
    qq_east text[],
    qq_south text[],
    qq_west text[],
    qq_rfid integer DEFAULT 0,
    qq_help text
);

ALTER TABLE public.tqq_questions ALTER COLUMN qq_qqid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tqq_questions_qq_qqid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.tqq_questions
    ADD CONSTRAINT tqq_questions_pkey PRIMARY KEY (qq_owner, qq_subject, qq_seq);

ALTER TABLE ONLY public.tqq_questions
    ADD CONSTRAINT tqq_questions_qq_qqid_key UNIQUE (qq_qqid);

CREATE INDEX idx_tqq_questions_qq_sbid ON public.tqq_questions USING btree (qq_sbid);

--
-- Name: trf_reference; Type: TABLE;
--

CREATE TABLE public.trf_reference (
    rf_rfid integer NOT NULL,
    rf_owner character varying(16) NOT NULL,
    rf_subject character varying(32) NOT NULL,
    rf_ref character varying(32) NOT NULL,
    rf_sbid integer,
    rf_desc character varying,
    rf_link character varying,
    rf_who character varying,
    rf_type character varying,
    rf_cntquestions smallint DEFAULT 0,
    rf_pubtype character varying(20) NOT NULL
);

ALTER TABLE public.trf_reference ALTER COLUMN rf_rfid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.trf_reference_rf_rfid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.trf_reference
    ADD CONSTRAINT trf_reference_pkey PRIMARY KEY (rf_owner, rf_subject, rf_ref);

ALTER TABLE ONLY public.trf_reference
    ADD CONSTRAINT trf_reference_rf_rfid_key UNIQUE (rf_rfid);

CREATE INDEX idx_trf_reference_rf_sbid ON public.trf_reference USING btree (rf_sbid);

--
-- Name: trt_reftype; Type: TABLE;
--

CREATE TABLE public.trt_reftype (
    rt_rtid integer NOT NULL,
    rt_type character varying NOT NULL,
    rt_title character varying(32)
);

ALTER TABLE public.trt_reftype ALTER COLUMN rt_rtid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.trt_reftype_rt_rtid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.trt_reftype
    ADD CONSTRAINT trt_reftype_pkey PRIMARY KEY (rt_type);

ALTER TABLE ONLY public.trt_reftype
    ADD CONSTRAINT trt_reftype_rt_rtid_key UNIQUE (rt_rtid);

--
-- Name: tsb_subject; Type: TABLE;
--

CREATE TABLE public.tsb_subject (
    sb_sbid integer NOT NULL,
    sb_owner character varying(16) NOT NULL,
    sb_subject character varying(32) NOT NULL,
    sb_title character varying(50),
    sb_cntquestions smallint DEFAULT 0,
    sb_cntreference smallint DEFAULT 0,
    sb_level character varying(16) DEFAULT ''::character varying
);

ALTER TABLE public.tsb_subject ALTER COLUMN sb_sbid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tsb_subject_sb_sbid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.tsb_subject
    ADD CONSTRAINT tsb_subject_pkey PRIMARY KEY (sb_owner, sb_subject);

ALTER TABLE ONLY public.tsb_subject
    ADD CONSTRAINT tsb_subject_sb_sbid_key UNIQUE (sb_sbid);

--
-- Name: tss_sessions; Type: TABLE;
--

CREATE TABLE public.tss_sessions (
    ss_ssid integer NOT NULL,
    ss_datetime timestamp with time zone NOT NULL,
    ss_usid integer NOT NULL
);

ALTER TABLE public.tss_sessions ALTER COLUMN ss_ssid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tss_sessions_ss_ssid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.tss_sessions
    ADD CONSTRAINT tss_sessions_pkey PRIMARY KEY (ss_ssid);

CREATE INDEX idx_tss_sessions_ss_usid ON public.tss_sessions USING btree (ss_usid);

--
-- Name: tuf_friends; Type: TABLE;
--

CREATE TABLE public.tuf_friends (
    uf_usid integer NOT NULL,
    uf_frid integer NOT NULL
);

ALTER TABLE ONLY public.tuf_friends
    ADD CONSTRAINT tuf_friends_pkey PRIMARY KEY (uf_usid, uf_frid);

--
-- Name: tuo_usersowner; Type: TABLE;
--

CREATE TABLE public.tuo_usersowner (
    uo_usid integer NOT NULL,
    uo_owner character varying(16) NOT NULL
);

ALTER TABLE ONLY public.tuo_usersowner
    ADD CONSTRAINT tuo_usersowner_pkey PRIMARY KEY (uo_usid, uo_owner);

--
-- Name: tup_userspwd; Type: TABLE;
--

CREATE TABLE public.tup_userspwd (
    up_usid integer NOT NULL,
    up_hash character varying(100),
    up_email text
);

ALTER TABLE ONLY public.tup_userspwd
    ADD CONSTRAINT tup_userspwd_pkey PRIMARY KEY (up_usid);

CREATE INDEX idx_tup_userspwd_up_email ON public.tup_userspwd USING btree (up_email);

--
-- Name: tus_users; Type: TABLE;
--

CREATE TABLE public.tus_users (
    us_usid integer NOT NULL,
    us_name character varying(100),
    us_email text NOT NULL,
    us_joined timestamp with time zone NOT NULL,
    us_fedid character varying(30),
    us_admin boolean,
    us_fedcountry character varying(16),
    us_provider character varying(30),
    us_skipcorrect boolean DEFAULT true,
    us_maxquestions integer DEFAULT 5,
    us_graph_user_months integer DEFAULT 24 NOT NULL,
    us_graph_top_months integer DEFAULT 24 NOT NULL,
    us_graph_recent_users integer DEFAULT 5 NOT NULL,
    us_graph_recent_avg integer DEFAULT 5 NOT NULL
);

ALTER TABLE public.tus_users ALTER COLUMN us_usid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tus_users_us_usid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.tus_users
    ADD CONSTRAINT tus_users_pkey PRIMARY KEY (us_usid);

ALTER TABLE ONLY public.tus_users
    ADD CONSTRAINT tus_users_us_email_key UNIQUE (us_email);

--
-- Name: twh_who; Type: TABLE;
--

CREATE TABLE public.twh_who (
    wh_whid integer NOT NULL,
    wh_who character varying(16) NOT NULL,
    wh_title character varying(32)
);

ALTER TABLE public.twh_who ALTER COLUMN wh_whid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.twh_who_wh_whid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.twh_who
    ADD CONSTRAINT twh_who_pkey PRIMARY KEY (wh_who);

ALTER TABLE ONLY public.twh_who
    ADD CONSTRAINT twh_who_wh_whid_key UNIQUE (wh_whid);

--
-- Name: xlg_logging; Type: TABLE;
--

CREATE TABLE public.xlg_logging (
    lg_lgid integer NOT NULL,
    lg_severity character(1),
    lg_caller character varying DEFAULT ''::character varying,
    lg_functionname character varying NOT NULL,
    lg_msg character varying NOT NULL,
    lg_datetime timestamp with time zone NOT NULL
);

ALTER TABLE public.xlg_logging ALTER COLUMN lg_lgid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.xlg_logging_lg_lgid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.xlg_logging
    ADD CONSTRAINT xlg_logging_pkey PRIMARY KEY (lg_lgid);
